version: '3'
services:
  notary:
    volumes:
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/Notary/node.conf:/etc/corda/node.conf
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/Notary/certificates:/opt/corda/certificates
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/Notary/logs:/opt/corda/logs
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/Notary/persistence:/opt/corda/persistence
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/Notary/cordapps:/opt/corda/cordapps
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/Notary/network-parameters:/opt/corda/network-parameters
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/Notary/additional-node-infos:/opt/corda/additional-node-infos
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/Notary/drivers:/opt/corda/drivers
    environment:
    - ACCEPT_LICENSE=YES
    ports:
    - "10003:10003"
    - "22022:2022"
    image: corda/corda-zulu-java1.8-4.8.5
    user: root
  partya:
    volumes:
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyA/node.conf:/etc/corda/node.conf
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyA/certificates:/opt/corda/certificates
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyA/logs:/opt/corda/logs
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyA/persistence:/opt/corda/persistence
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyA/cordapps:/opt/corda/cordapps
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyA/network-parameters:/opt/corda/network-parameters
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyA/additional-node-infos:/opt/corda/additional-node-infos
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyA/drivers:/opt/corda/drivers
    environment:
    - ACCEPT_LICENSE=YES
    ports:
    - "10006:10006"
    - "22024:22024"
    image: corda/corda-zulu-java1.8-4.8.5
    user: root
  partyb:
    volumes:
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyB/node.conf:/etc/corda/node.conf
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyB/certificates:/opt/corda/certificates
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyB/logs:/opt/corda/logs
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyB/persistence:/opt/corda/persistence
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyB/cordapps:/opt/corda/cordapps
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyB/network-parameters:/opt/corda/network-parameters
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyB/additional-node-infos:/opt/corda/additional-node-infos
    - /root/IndividualProject_2021_David.Akinsanya/cordapp/cordapp/build/nodes/PartyB/drivers:/opt/corda/drivers
    environment:
    - ACCEPT_LICENSE=YES
    ports:
    - "10009:10009"
    - "22026:22026"
    image: corda/corda-zulu-java1.8-4.8.5
    user: root
